### ISSUE TITLE
Landmarks on top nav?

### ISSUE THREAD

**Issue by mmafe** [ccswbs/web-components#2]
I'm wondering if we need a navigation landmark on the top nav. Currently it's a banner, which makes sense, but I do think having the navigation landmark would improve accessibility. Thoughts on this?

**Comment by RazaMM** [comment]
Do we want to wrap all of the header content in a `<nav>` tag or each separate bar?

**Comment by RazaMM** [comment]
Or maybe something else entirely? I do agree that the navigation role would better suit what the header is meant for semantically

**Comment by mmafe** [comment]
I've started reading this thread...haven't finished it yet, but it may help: https://dev.to/masakudamatsu/don-t-nest-nav-inside-header-do-nest-the-hamburger-menu-button-inside-nav-6cp

**Comment by mmafe** [comment]
I'm taking a sampling...

MDN web docs nests the navigation landmark inside the banner.

<img width="1726" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/1e30040a-fe1a-4c87-8a52-73a11a539664">

W3C nests nav inside banner.

<img width="1727" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/d81a277e-224f-4660-b9ee-77bf90706bf4">

WebAIM manages to get by without nesting. 
<img width="1396" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/8a304ab8-19a4-459f-a160-c97f82c7b076">

I'm thinking [Updated comment] if we can do it on a separate bar, let's do that...otherwise, we should nest. (I figure one of those options is better than nothing. Also the previous article mentioned that screen-readers sometimes do not provide a notification about nested landmarks. That's something that could change in future, so I'm willing to nest if separate bars aren't an option.)

**Comment by mmafe** [comment]
Although I just noticed you asked if I wanted it in a separate bar. If you can get by with it in a separate bar, that would be awesome...but if not, then nesting. (I've updated my comment above to reflect this.)

**Comment by mmafe** [comment]
It looks Tenon.io used a nested nav in the banner.
<img width="1726" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/f32abedc-fcc6-4b38-90c2-30aaa274677b">

And LevelAccess did the same (nested nav in banner)
<img width="1722" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/006cfc9d-0f56-47b9-b734-d518096f3a4a">

**Comment by mmafe** [comment]
@RazaMM The more that I think about it, the more I feel like nesting it. The structure is nested, so I feel like that makes the most sense.

**Comment by RazaMM** [comment]
I agree, looking into it I think doing a separate bar would be a bit too difficult and messy. Ill update with nested nav
